In [1]:
#Step 1: Importing the dataset
#Step 2: Data pre-processing
#Step 3: Splitting the test and train sets
#Step 4: Fitting the KNN model to the training set
#Step 5: Evaluate the model

import numpy as np
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()
x = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.5)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.91      0.91      0.91        23
           2       0.92      0.92      0.92        24

    accuracy                           0.95        75
   macro avg       0.94      0.94      0.94        75
weighted avg       0.95      0.95      0.95        75

[[28  0  0]
 [ 0 21  2]
 [ 0  2 22]]
0.9466666666666667
